### ISSUE TITLE
Gnome 3.16 is there.

### ISSUE THREAD

**Issue by unixhelden** [philipphoffmann/gnome3-jenkins-indicator#67]
Could you please update your Extension so it does work with 3.16?

**Comment by philipphoffmann** [comment]
You're right, I will look into it.

**Comment by philipphoffmann** [comment]
Sorry, I just figured that there are no packages in the ubuntu utopic ppa for 3.16 yet. You can try to modify the plugins metadata though, might be that it works out of the box.

**Comment by juanwolf** [comment]
:+1:

**Comment by philipphoffmann** [comment]
done
