### ISSUE TITLE
Job name filters are not properly applied.

### ISSUE THREAD

**Issue by sergiy-kozak** [philipphoffmann/gnome3-jenkins-indicator#72]
According to the documentation, the job name filters can be used as the comma-separated list of expressions. One of allowed usages is adding negation to specific expression like !.*part-of-the-name1.

Provided the job names set ("job-xxx1-name", "job-xxx2-name", "job-xxx3-name", "job-yyy9-name", "job-yyy5-name") and filter string "!.\*xxx3.\*,!job-yyy.*", the list of shown jobs in the popover still contains all the test jobs instead of showing only ("job-xxx1-name", "job-xxx2-name") ones.

**Comment by philipphoffmann** [comment]
fixed
