### ISSUE TITLE
register the estensions as a jenkins plugin

### ISSUE THREAD

**Issue by andcoz** [philipphoffmann/gnome3-jenkins-indicator#75]
You should *register* the extension in the ["official" jenkins plug-in list](https://wiki.jenkins-ci.org/display/JENKINS/Plugins). 

There are a lot of similar tools: [Windows](https://wiki.jenkins-ci.org/display/JENKINS/Hudson+Tray+Application), [Android](https://wiki.jenkins-ci.org/display/JENKINS/Hudson+Monitor+for+Android), [Chumby](https://wiki.jenkins-ci.org/display/JENKINS/Hudson+Monitor+for+Chumby) :-O, [Windows](https://wiki.jenkins-ci.org/display/JENKINS/Hudson+Monitor+Gadget+for+Microsoft+Sidebar.) (again), [iPhone](https://wiki.jenkins-ci.org/display/JENKINS/Hudson+Helper+iPhone+and+iPod+Touch+App), [firefox](https://wiki.jenkins-ci.org/display/JENKINS/Firefox+Add-on+Build+Monitor). 

Why not yours?

**Comment by philipphoffmann** [comment]
Actually, it is already listed. Not in the plugins list though because its not actually a Jenkins plugin.

Its listed here: https://wiki.jenkins-ci.org/display/JENKINS/Use+Jenkins (search for "Jenkins Indicator Gnome 3 Extension")

**Comment by andcoz** [comment]
Ops ... It seems that I searched in the wrong place. :-P

Very well, thank you

**Comment by philipphoffmann** [comment]
yeah, also took myself a while to find it, the jenkins wiki hierarchy is a bit wild :D
